### ISSUE TITLE
Skip downloading media if it's already hosted on info.defcon.org

### ISSUE THREAD

**Issue by aNullValue** [junctor/hackertracker-info#2]

**Comment by aNullValue** [comment]
Media that is already hosted on info.defcon.org should not be re-downloaded from Firebase; use the media URL as-is.

**Comment by cak** [comment]
@aNullValue This should be done as part of this refactor: https://github.com/junctor/hackertracker-info/commit/0d73f7f334f8e97e111c1677a4496499647362e6
