### ISSUE TITLE
Show media on detail pages

### ISSUE THREAD

**Issue by aNullValue** [junctor/hackertracker-info#5]

**Comment by cak** [comment]
@aNullValue Org details that have media now have media[0] displayed below title.

**Comment by aNullValue** [comment]
Thank you! :)

**Comment by aNullValue** [comment]
Err, I'm dumb. That was just /org.

**Comment by cak** [comment]
To be fair, I missed this as well.

**Comment by cak** [comment]
@aNullValue This should be now complete, do we have any current events with media?

**Comment by aNullValue** [comment]
/event/?id=55843 should have media on it, but it doesn't seem to be showing

**Comment by cak** [comment]
Thanks! I'll look into.

**Comment by cak** [comment]
Fixed with media being added to events document.
