### ISSUE TITLE
Ensure that speaker.events is not being used

### ISSUE THREAD

**Issue by aNullValue** [junctor/hackertracker-info#7]
In Firebase, I recently removed array "events" from "speaker", believing that it was no longer being used by any clients. This turned out to have been incorrect. :) When speaker.events does not exist, the website throws an "internal exception" and stops, whenever attempting to get information about a speaker. 

Quickly mitigated issue by rolling back the Firebase deploy code to the version before that array was removed, then redeploying to Firebase, and then rebuilding the website.

Bug reported by The Dark Tangent

**Comment by cak** [comment]
@aNullValue Thank you, speakers.events has been removed and replaced with a look up on `events.json`, please test and verify,

**Comment by aNullValue** [comment]
This seems to be fixed. Thank you! :)
